#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title BigBlueButton Users
graph_vlabel bbbuser
bbbuser.label bbbuser
EOM
        exit 0;;
esac

printf "bbbuser.value "
mongo --quiet mongodb://127.0.1.1:27017/meteor --eval "db.users.count({connectionStatus: 'online'})"
